export const events = [
  {
    slug: "react-conf-2024",
    image: "/images/event1.png",
    title: "React Conf 2024",
    location: "San Francisco, CA",
    date: "March 15, 2024",
    time: "9:00 AM - 6:00 PM",
    agenda: [
      "9:00 AM - Registration and coffee",
      "10:00 AM - Keynote: The future of React",
      "1:00 PM - Server Components workshop",
      "4:00 PM - Community lightning talks",
    ],
  },
  {
    slug: "nextjs-summit",
    image: "/images/event2.png",
    title: "Next.js Summit",
    location: "Austin, TX",
    date: "April 22, 2024",
    time: "10:00 AM - 5:00 PM",
    agenda: [
      "10:00 AM - Opening remarks",
      "11:00 AM - App Router deep dive",
      "2:00 PM - Deploying at the edge",
      "4:00 PM - Panel: Scaling Next.js",
    ],
  },
  {
    slug: "javascript-world",
    image: "/images/event3.png",
    title: "JavaScript World Conference",
    location: "New York, NY",
    date: "May 8, 2024",
    time: "8:30 AM - 7:00 PM",
    agenda: [
      "8:30 AM - Doors open",
      "9:30 AM - State of JavaScript",
      "1:00 PM - TypeScript at scale",
      "5:00 PM - Closing keynote",
    ],
  },
  {
    slug: "ai-hackathon-2024",
    image: "/images/event4.png",
    title: "AI Innovation Hackathon",
    location: "Seattle, WA",
    date: "June 14-16, 2024",
    time: "48 Hours",
    agenda: [
      "Day 1 - Team forming and kickoff",
      "Day 2 - Build and mentor sessions",
      "Day 3 - Project demos",
      "Day 3 - Judging and awards",
    ],
  },
  {
    slug: "web3-developer-meetup",
    image: "/images/event5.png",
    title: "Web3 Developer Meetup",
    location: "Miami, FL",
    date: "July 20, 2024",
    time: "6:00 PM - 9:00 PM",
    agenda: [
      "6:00 PM - Networking",
      "6:45 PM - Smart contract security talk",
      "7:45 PM - Live coding demo",
      "8:30 PM - Open discussion",
    ],
  },
  {
    slug: "fullstack-conference",
    image: "/images/event6.png",
    title: "Full Stack Conference",
    location: "Denver, CO",
    date: "August 12, 2024",
    time: "9:00 AM - 6:00 PM",
    agenda: [
      "9:00 AM - Registration",
      "10:00 AM - Frontend architecture",
      "1:30 PM - Database design patterns",
      "4:30 PM - Q&A with speakers",
    ],
  },
  {
    slug: "devops-unleashed",
    image: "/images/event1.png",
    title: "DevOps Unleashed",
    location: "Chicago, IL",
    date: "September 5, 2024",
    time: "8:00 AM - 5:30 PM",
    agenda: [
      "8:00 AM - Breakfast and check-in",
      "9:00 AM - CI/CD pipelines that scale",
      "12:30 PM - Kubernetes in production",
      "4:00 PM - Incident response panel",
    ],
  },
  {
    slug: "mobile-dev-summit",
    image: "/images/event2.png",
    title: "Mobile Development Summit",
    location: "Los Angeles, CA",
    date: "October 18, 2024",
    time: "9:30 AM - 6:00 PM",
    agenda: [
      "9:30 AM - Welcome",
      "10:30 AM - Cross-platform strategies",
      "2:00 PM - Native performance tuning",
      "5:00 PM - App Store best practices",
    ],
  },
  {
    slug: "cybersecurity-conference",
    image: "/images/event3.png",
    title: "Cybersecurity Conference",
    location: "Boston, MA",
    date: "November 2, 2024",
    time: "8:00 AM - 7:00 PM",
    agenda: [
      "8:00 AM - Registration",
      "9:00 AM - Threat landscape 2024",
      "1:00 PM - Hands-on penetration testing",
      "5:30 PM - Zero trust architecture",
    ],
  },
  {
    slug: "data-science-hackathon",
    image: "/images/event4.png",
    title: "Data Science Hackathon",
    location: "San Diego, CA",
    date: "December 7-9, 2024",
    time: "72 Hours",
    agenda: [
      "Day 1 - Dataset release and kickoff",
      "Day 2 - Model building",
      "Day 3 - Final submissions",
      "Day 3 - Leaderboard and prizes",
    ],
  },
  {
    slug: "cloud-native-meetup",
    image: "/images/event5.png",
    title: "Cloud Native Meetup",
    location: "Portland, OR",
    date: "January 15, 2025",
    time: "6:30 PM - 9:00 PM",
    agenda: [
      "6:30 PM - Doors open and pizza",
      "7:00 PM - Serverless patterns talk",
      "8:00 PM - Observability demo",
      "8:45 PM - Networking",
    ],
  },
  {
    slug: "frontend-masters",
    image: "/images/event6.png",
    title: "Frontend Masters Conference",
    location: "Nashville, TN",
    date: "February 28, 2025",
    time: "9:00 AM - 5:00 PM",
    agenda: [
      "9:00 AM - Registration",
      "10:00 AM - Modern CSS techniques",
      "1:00 PM - Accessibility workshop",
      "4:00 PM - Closing remarks",
    ],
  },
];
